name: campuscash
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  sqflite: ^2.0.4
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  image_picker: ^1.1.2
  cloud_firestore: ^5.0.1
  cloud_functions: ^5.0.1

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/Group 520 (4).png
    - assets/images/Group 520 (5).png
    - assets/images/Group 521.png
    - assets/images/Illustration.png
    - assets/images/Illustration 1.png
    - assets/images/Illustration (1).png
    - assets/images/logo campus cash.jpg
    - assets/images/anggaran.jpg



